# Generated by Django 3.2.7 on 2021-09-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
